"use client"
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../component/Navbar'
import HeroSection from '../component/HeroSection'
import { ThemeProvider } from 'next-themes'
import ProductsSection from '../component/ProductsSection'
import AboutSection from '../component/AboutSection'
import Footer from '../component/Footer'
import Contacts from '../component/Contacts';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <ThemeProvider enableSystem={true} attribute="class">
        <Navbar />
      <main id="home">
        <HeroSection />
        <ProductsSection />
        <AboutSection />
        <Contacts />
      </main>
      <Footer />
      </ThemeProvider>
    </>
  )
}
